### PR TITLE
chore: add index on traceID

### PR DESCRIPTION
**Pull request by ankitnayan**
adding index on traceID should enable searching by traceID much faster

### CODE REVIEW

**Comment by ankitnayan** [comment]
this did not work in reducing granules scanned. Needs further investigation

**Comment by nityanandagohain** [comment]
try using bloom filter instead of tokenbf. also increase the size of the filter

**Comment by ankitnayan** [comment]
> try using bloom filter instead of tokenbf? also increase the size of the filter

Can you suggest the size to use?

**Comment by srikanthccv** [comment]
@nityanandagohain please suggest the size. The https://github.com/SigNoz/signoz-otel-collector/pull/365 is waiting on this which will help in PRs like https://github.com/SigNoz/signoz/issues/3184

**Comment by nityanandagohain** [comment]
If a granule has around 4000 unique trace_id ( 8192 total rows), 

The size of index = 10KB with 5 hash functions will give us probability of false positive 0.000314144 (1 in 3183).

https://hur.st/bloomfilter/?n=4000&p=&m=90000&k=5 

let's start with 10KB and 5 hash functions ?

**Comment by ankitnayan** [comment]
this PR can wait

**Comment by nityanandagohain** [comment]
https://github.com/SigNoz/signoz-otel-collector/blob/main/cmd/signozschemamigrator/schema_migrator/traces_migrations.go

**Pull request closed without merging**
