### PR TITLE
Bump upstream version to 0.88.0

### PR DESCRIPTION
**Pull request by srikanthccv**
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/200
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/167

### CODE REVIEW

**Review by makeavish — APPROVED** [review]
Looks like there are no changes related Traces in upgrade.
We also need to update the binary links in [website](https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/) and onboarding docs.

**Review by nityanandagohain — COMMENTED** [review]
At signoz QS, we depend on v 0.79 we should update that as well.

https://github.com/SigNoz/signoz/blob/develop/go.mod

**Comment by srikanthccv** [comment]
I will update it when we bump the `signoz-otel-collector` docker image version in that repo.

**Comment by prashant-shahi** [comment]
@srikanthccv are we good to create the `v0.88.0` release tag?

**Comment by srikanthccv** [comment]
No, a couple of other PRs can get merged.

**Pull request merged**
