### PR TITLE
fix: upgrade clickhouse client and set maxopenconnections

### PR DESCRIPTION
**Pull request by nityanandagohain**
It fixes this issues i.e

1) **When there is data being filled to queue with num consumers >1 then it panics and shut down**.
  <details>
      <summary>stacktrace</summary>
  ```
  2023-11-02T14:04:31.143+0530	error	exporterhelper/queued_retry.go:307	Dropping data because sending_queue is full. Try increasing queue_size.	{"kind": "exporter", "data_type": "logs", "name": "clickhouselogsexporter", "dropped_items": 512}
  go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/queued_retry.go:307
  go.opentelemetry.io/collector/exporter/exporterhelper.NewLogsExporter.func2
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/logs.go:104
  go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/consumer@v0.79.0/logs.go:25
  go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/consumer@v0.79.0/logs.go:25
  go.opentelemetry.io/collector/receiver/otlpreceiver/internal/logs.(*Receiver).Export
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/receiver/otlpreceiver@v0.79.0/internal/logs/otlp.go:40
  go.opentelemetry.io/collector/pdata/plog/plogotlp.rawLogsServer.Export
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rcv0012/plog/plogotlp/grpc.go:82
  go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/logs/v1._LogsService_Export_Handler.func1
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rcv0012/internal/data/protogen/collector/logs/v1/logs_service.pb.go:311
  go.opentelemetry.io/collector/config/configgrpc.enhanceWithClientInformation.func1
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector@v0.79.0/config/configgrpc/configgrpc.go:400
  google.golang.org/grpc.getChainUnaryHandler.func1
	  /Users/nityanandagohain/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:1154
  go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.42.0/interceptor.go:344
  google.golang.org/grpc.chainUnaryInterceptors.func1
	  /Users/nityanandagohain/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:1145
  go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/logs/v1._LogsService_Export_Handler
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rcv0012/internal/data/protogen/collector/logs/v1/logs_service.pb.go:313
  google.golang.org/grpc.(*Server).processUnaryRPC
	  /Users/nityanandagohain/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:1335
  google.golang.org/grpc.(*Server).handleStream
	  /Users/nityanandagohain/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:1712
  google.golang.org/grpc.(*Server).serveStreams.func1.1
	  /Users/nityanandagohain/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:947
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10725a830]
  
  goroutine 63 [running]:
  github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Encoder).UInt8(0x0, 0x1)
	  /Users/nityanandagohain/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.12/lib/binary/encoder.go:72 +0x30
  github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Encoder).Byte(0x0, 0x1)
	  /Users/nityanandagohain/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.12/lib/binary/encoder.go:52 +0x30
  github.com/ClickHouse/clickhouse-go/v2.(*connect).sendQuery(0x14001ef0000, {0x14001cf01c0, 0x39}, 0x140010cdb80)
	  /Users/nityanandagohain/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.12/conn_send_query.go:28 +0x144
  github.com/ClickHouse/clickhouse-go/v2.(*connect).prepareBatch(0x14001ef0000, {0x109255318, 0x140016cc0e0}, {0x14001cf01c0, 0x39}, 0x14001e43720)
	  /Users/nityanandagohain/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.12/conn_batch.go:45 +0x2d8
  github.com/ClickHouse/clickhouse-go/v2.(*clickhouse).PrepareBatch(0x14001f04f40, {0x109255318, 0x140016cc0e0}, {0x14001498f00, 0x32})
	  /Users/nityanandagohain/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.12/clickhouse.go:146 +0x134
  github.com/SigNoz/signoz-otel-collector/exporter/clickhouselogsexporter.(*clickhouseLogsExporter).pushLogsData(0x14001f102a0, {0x109255318, 0x140016cc0e0}, {0x14001da0b40})
	  /Users/nityanandagohain/projects/signoz-otel-collector/signoz-otel-collector/exporter/clickhouselogsexporter/exporter.go:135 +0x360
  go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export(0x14001da99e0, {0x109255318, 0x140016cc0e0})
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/logs.go:54 +0x54
  go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0x14001744e08, {0x109269e48, 0x14001da99e0})
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/common.go:197 +0x138
  go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0x140017c0280, {0x109269e48, 0x14001da99e0})
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/queued_retry.go:384 +0x4e4
  go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0x140017f23c0, {0x109269e48, 0x14001da99e0})
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/logs.go:124 +0xcc
  go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x109269e48, 0x14001da99e0})
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/queued_retry.go:195 +0x48
  go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1()
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/internal/bounded_memory_queue.go:47 +0x108
  created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers in goroutine 60
	  /Users/nityanandagohain/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/internal/bounded_memory_queue.go:42 +0x144
	  ```
	  </details>
  	

After upgrading the clickhouse client  it drop's data but doesn't panic and shutdown.

2) Setting MaxOpenConns = num_consumers. This solves the `prepareBatch:clickhouse: acquire conn timeout`

### CODE REVIEW

**Comment by makeavish** [comment]
Have you tried running migrations after adding new migrations? Asking you this as go migrate uses older version of clickhouse go and it might causes issues because of that.

**Comment by nityanandagohain** [comment]
ahh no, haven't run migrations, let me try out.

**Comment by srikanthccv** [comment]
Just trying to follow the fix. 

1. The default `num_consumers` is 10 from the collector side. 
2. The default `MaxOpenConns` = `MaxIdleConns` + 5 and 
3. `MaxIdleConns` is 5 by default

So the default `MaxOpenConns` is 10 and MaxOpenConns = num_consumers is already satisfied in the current setup, right? I doubt if this change is really fixing it. Does it consistently work with this fix and fail if the changes are not there?

**Comment by srikanthccv** [comment]
It's also possible updating the clickhouse-go indirectly fixed the `prepareBatch:clickhouse: acquire conn timeout` not just the encoding panic error.

**Comment by nityanandagohain** [comment]
So basically the `acquire timeout` issue was not reproducable with the previous clickhouse client, as soon as a increase consumers and send a burst of data it panics and shuts down i.e issue 1

Now after upgrading issue 1 was solved.


Coming to issue 2. Now I tested by
*  changing num consumers to 10 and then max connections to 5. 
* Sending a burst of data  and the error occured i.e entire ingestion was blocked and connection acquire timeout.
* This continued until i set num_consumers = max_connections.

Though I agree that if the above was the case then in prod it shouldn't have happened.

**Comment by nityanandagohain** [comment]
@makeavish the migrations are running fine, I didn't see any error.

**Comment by nityanandagohain** [comment]
@srikanthccv in the latest commit, I have changed max_connections = num_consumers + 1, as there is a usage collector running which basically tries to acquire one more connection and that is when the issue occurs.

**Comment by srikanthccv** [comment]
Even with the last commit, I wonder if this change fixes the main issue. I followed the discussion here https://github.com/ClickHouse/clickhouse-go/issues/873. The maintainer doesn't say that current client connections are blocked indefinitely if one of the new calls to acquire connection times out. Once we reach the limit and no existing connections are released within timeout, then we get `acquire conn timeout`, which is expected. 

Let's consider the high-volume case and usage reporting. One of the consumers might not have gotten a connection and failed to prepare the batch. But we expect the usage reporter to eventually release the connection, right? There might be some loss of data, but that failure in the logs exporter should not be permanent where data ingestion is blocked indefinitely. What do you think? How frequent was this `acquire conn timeout` in the error logs? Do you see any place in our code where a connection is never released and leads to forever  `acquire conn timeout`?

**Comment by makeavish** [comment]
> What do you think? How frequent was this acquire conn timeout in the error logs? Do you see any place in our code where a connection is never released and leads to forever acquire conn timeout?

I think the PR is valid and should be merged along with metrics and traces changes. We should investigate why connections are blocked. Created [issue](https://github.com/SigNoz/signoz-otel-collector/issues/222) another for the same.

**Comment by nityanandagohain** [comment]
> Do you see any place in our code where a connection is never released and leads to forever acquire conn timeout

@srikanthccv  the case you are mentioning is easily reproducable in our code.

* Set num_consurs = max_connections
* Set usage collection interval to 1 sec https://github.com/SigNoz/signoz-otel-collector/blob/39aa62326f16cd76e4b3a263ceccb2c149f6dfc7/usage/common.go#L17
* Run this code to generate a burst of data https://www.notion.so/signoz/Logs-Sending-queue-error-f13a078c9a9f4ae48a61aae96df96cbd?pvs=4#866378688a47494c9ab375f2d4a1fb69

wait for sometime and you won't be able to send any data and number of logs will not change on clickhouse.

**Comment by srikanthccv** [comment]
>I think the PR is valid and should be merged along with metrics and traces changes. We should investigate why connections are blocked.

It's valid, but the assumptions/statements that are believed to be true are not correct and the confidence expressed in the fix does not match with the theoretical analysis. I don't have any issues with getting this merged and further investigating. I asked more questions that would help dig deeper. 


> Set usage collection interval to 1 sec

You are creating a busy loop by setting it to one second and depriving the conns for others deliberately. But that's not how it happens in production. The usage reporting is done once in a while and the connection should be released afterwards. What does it do if you set it to 5 mintues? Does it still not write any logs? Is there any other reproducible case?

**Comment by nityanandagohain** [comment]
Yeah agree about the 1s, but I was trying to replicate that all consumers being busy and usage collector running at the same time.

**Review by srikanthccv — APPROVED** [review]
We got on a call and found a clear reproducible case that can be further investigated

**Review by makeavish — APPROVED** [review]

**Pull request merged**
