### PR TITLE
feat: add new tag types

### PR DESCRIPTION
**Pull request by makeavish**

### CODE REVIEW

**Comment by srikanthccv** [comment]
@makeavish was there any discussion around supporting array and map types?

**Comment by makeavish** [comment]
> @makeavish was there any discussion around supporting array and map types?

Yes, discussed this with @ankitnayan. For now, we are writing arrays and maps as string and users will have to use string operators to search through them. We might support them in future.

**Review by srikanthccv — APPROVED** [review]

**Comment by ankitnayan** [comment]
> @makeavish was there any discussion around supporting array and map types?

array and map types for attributes?

**Comment by makeavish** [comment]
> > @makeavish was there any discussion around supporting array and map types?
> 
> array and map types for attributes?

Yes @ankitnayan

**Comment by srikanthccv** [comment]
@makeavish is there anything pending here? otherwise, please merge.

**Comment by makeavish** [comment]
Was waiting for https://github.com/SigNoz/signoz/pull/2029 to be approved as these changes are breaking changes and have to shipped together.

**Pull request merged**
