### PR TITLE
chore: use map to reduce writes to clickhouse tag tables

### PR DESCRIPTION
**Pull request by makeavish**
fix: https://github.com/SigNoz/engineering-pod/issues/1028

### CODE REVIEW

**Comment by srikanthccv** [comment]
Please share how you measured the change and the difference observed with some non-trivial workloads.

**Comment by makeavish** [comment]
With this change CPU time of writeTagBatch decreases by 30-70% depending on the duplicates attributes in batch.
Tested this with Flask application running at 100rps. Didn't see any significant changes in memory profile.

**Comment by srikanthccv** [comment]
I think 100 rps is not enough for this kind of benchmark. Can you use some synthetic load generator like https://github.com/Omnition/synthetic-load-generator to create a much higher load around 5k-10k span/s? I would put a load on the collector as much as it starts to give the context deadline error and see when it reaches this peak state before and after the change. And it helps if you share the before and after profiles as well.

**Comment by makeavish** [comment]
> I think 100 rps is not enough for this kind of benchmark. Can you use some synthetic load generator like https://github.com/Omnition/synthetic-load-generator to create a much higher load around 5k-10k span/s? I would put a load on the collector as much as it starts to give the context deadline error and see when it reaches this peak state before and after the change. And it helps if you share the before and after profiles as well.

I think synthetic load generator doesn't reproduce real-world use case well so tried 1000rps(generating around 5-6k spans/s) with flask app with DB calls. The result was the same.

**Review by srikanthccv — APPROVED** [review]

**Comment by ankitnayan** [comment]
this PR should be part of next release

**Pull request merged**
