### PR TITLE
Stop wrting to v1 tag attributes table

### PR DESCRIPTION
**Pull request by srikanthccv**
See https://github.com/SigNoz/signoz/pull/6616

Fixes https://github.com/SigNoz/signoz-otel-collector/issues/467

### CODE REVIEW

**Comment by nityanandagohain** [comment]
You will have to write migration first for the users who use the existing tables in clickhouse query eg:- our ingestion dashboard  https://github.com/SigNoz/dashboards/blob/daee7a272aa470c06d0b000a09b9ef39fcd8dc11/signoz-ingestion-analysis/signoz-ingestion-analysis-v1.json

**Comment by srikanthccv** [comment]
@nityanandagohain We are not using this table anywhere in that dashboard. We are only using keys table.

**Comment by srikanthccv** [comment]
I do not expect anyone to know about this table because it's not documented. Do you recall writing any queries on v1 tables for anyone?

**Comment by srikanthccv** [comment]
there are [users](https://saasmonitor.us.signoz.cloud/logs/logs-explorer?compositeQuery=%257B%2522queryType%2522%253A%2522builder%2522%252C%2522builder%2522%253A%257B%2522queryData%2522%253A%255B%257B%2522dataSource%2522%253A%2522logs%2522%252C%2522queryName%2522%253A%2522A%2522%252C%2522aggregateOperator%2522%253A%2522count%2522%252C%2522aggregateAttribute%2522%253A%257B%2522id%2522%253A%2522------false%2522%252C%2522dataType%2522%253A%2522%2522%252C%2522key%2522%253A%2522%2522%252C%2522isColumn%2522%253Afalse%252C%2522type%2522%253A%2522%2522%252C%2522isJSON%2522%253Afalse%257D%252C%2522timeAggregation%2522%253A%2522rate%2522%252C%2522spaceAggregation%2522%253A%2522sum%2522%252C%2522functions%2522%253A%255B%255D%252C%2522filters%2522%253A%257B%2522op%2522%253A%2522AND%2522%252C%2522items%2522%253A%255B%257B%2522id%2522%253A%25229ae427a0%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522hostname%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522resource%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522hostname--string--resource--false%2522%257D%252C%2522op%2522%253A%2522exists%2522%252C%2522value%2522%253A%2522%2522%257D%252C%257B%2522id%2522%253A%25221a82ced6%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522clickhouse.query_log.query%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522clickhouse.query_log.query--string--tag--true%2522%257D%252C%2522op%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522tag_attributes%2522%257D%252C%257B%2522id%2522%253A%2522be411108%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522clickhouse.query_log.query%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522clickhouse.query_log.query--string--tag--true%2522%257D%252C%2522op%2522%253A%2522ncontains%2522%252C%2522value%2522%253A%2522INSERT%2522%257D%252C%257B%2522id%2522%253A%2522a02d2e8c%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522clickhouse.query_log.query%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522clickhouse.query_log.query--string--tag--true%2522%257D%252C%2522op%2522%253A%2522ncontains%2522%252C%2522value%2522%253A%2522UNION%2520DISTINCT%2522%257D%252C%257B%2522id%2522%253A%2522ef9a49c1%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522clickhouse.query_log.query%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522clickhouse.query_log.query--string--tag--true%2522%257D%252C%2522op%2522%253A%2522ncontains%2522%252C%2522value%2522%253A%252225000%2522%257D%252C%257B%2522id%2522%253A%2522ad6bba5c%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522k8s.namespace.name%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522resource%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522k8s.namespace.name--string--resource--false%2522%257D%252C%2522op%2522%253A%2522%21%253D%2522%252C%2522value%2522%253A%2522saasmonitor%2522%257D%252C%257B%2522id%2522%253A%25228a1d5258%2522%252C%2522key%2522%253A%257B%2522key%2522%253A%2522clickhouse.query_log.log_comment.dashboardID%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522clickhouse.query_log.log_comment.dashboardID--string--tag--true%2522%257D%252C%2522op%2522%253A%2522%21%253D%2522%252C%2522value%2522%253A%2522%2522%257D%255D%257D%252C%2522expression%2522%253A%2522A%2522%252C%2522disabled%2522%253Afalse%252C%2522stepInterval%2522%253A60%252C%2522having%2522%253A%255B%255D%252C%2522limit%2522%253Anull%252C%2522orderBy%2522%253A%255B%257B%2522columnName%2522%253A%2522timestamp%2522%252C%2522order%2522%253A%2522desc%2522%257D%255D%252C%2522groupBy%2522%253A%255B%257B%2522key%2522%253A%2522k8s.namespace.name%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522resource%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522k8s.namespace.name--string--resource--false%2522%257D%252C%257B%2522key%2522%253A%2522clickhouse.query_log.log_comment.dashboardID%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%252C%2522id%2522%253A%2522clickhouse.query_log.log_comment.dashboardID--string--tag--true%2522%257D%255D%252C%2522legend%2522%253A%2522%2522%252C%2522reduceTo%2522%253A%2522avg%2522%257D%255D%252C%2522queryFormulas%2522%253A%255B%255D%257D%252C%2522promql%2522%253A%255B%257B%2522name%2522%253A%2522A%2522%252C%2522query%2522%253A%2522%2522%252C%2522legend%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%257D%255D%252C%2522clickhouse_sql%2522%253A%255B%257B%2522name%2522%253A%2522A%2522%252C%2522legend%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%252C%2522query%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522643e97e4-3904-4e68-a9e1-2fffc771b9b6%2522%257D&options=%7B%22maxLines%22%3A2%2C%22format%22%3A%22list%22%2C%22selectColumns%22%3A%5B%7B%22key%22%3A%22timeTaken%22%2C%22dataType%22%3A%22float64%22%2C%22type%22%3A%22tag%22%2C%22isColumn%22%3Afalse%2C%22isJSON%22%3Afalse%2C%22id%22%3A%22timeTaken--float64--tag--false%22%7D%5D%2C%22fontSize%22%3A%22small%22%7D&relativeTime=3d&panelTypes=%22table%22&viewName=%22%22&viewKey=%22%22), i will update them

**Review by nityanandagohain — APPROVED** [review]

**Pull request merged**
