### PR TITLE
#167 update dependencies

### LINKED ISSUE #167: Update Open telemetry contrib packages to 0.80.0
Hi there, 
I have the requirement to display the system uptime in a dashboard. Therefore, I need at least 
github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerstatsreceiver v0.80.0
as stated in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CHANGELOG.md
As I see it, the policy is to build a release for every of these versions, since opentelemetry-collector-contrib does not adhire to semantic versioning. 
Therefore, it would be nice, if the versions 0.80, 0.81, 0.82 and 0.83 could be built :)

Greetings!

### PR DESCRIPTION
**Pull request by svsk417**
Closes #167

### CODE REVIEW

**Comment by svsk417** [comment]
Hi! I tested this as good as I could. I executed the go application and it did the migrations etc. But I am not very proficient in Go, so please review carefully.
I left the dependency github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dotnetdiagnosticsreceiver v0.76.3 in place, as there was no new version and prometheusexecreceiver at 0.82.0, since it was deprecated and no version 0.83.0 was published

**Comment by svsk417** [comment]
The build is failing, because the CI uses go version 1.19 and I tested it locally with 1.21. 
The function `errors.join` [was introduced in go 1.20](https://tip.golang.org/doc/go1.20) and therefore cannot be found. I updated the actions to use 1.21

**Comment by svsk417** [comment]
Hi @prashant-shahi!
Can you trigger another build? 
Let's see, if it works now :)

**Comment by svsk417** [comment]
Hi @prashant-shahi,
can you take a look at this? :)

**Comment by prashant-shahi** [comment]
Hi @svsk417, apologies for late response.

About the linked issue and the PR, usually, we have thorough internal tests before bumping up to new OtelCollector version.

This is critical to not only making it work for SigNoz cluster to run properly.
But also users who might have external clients still running on older version of OtelCollectors.

Nevertheless, let me share the PR and linked issue with the maintainers the repository.

**Comment by svsk417** [comment]
Hi @prashant-shahi,  I deleted my changes since opentelemetry-collector-contrib version 0.85.0 has been released. It would be nice, if you bump to that version. :) If I shall do another PR with that version just let me know. I will be waiting for your response before beginning to not have merge conflicts making the PR obsolete.

**Comment by prashant-shahi** [comment]
@svsk417 Continuing the conversation in the issue thread: https://github.com/SigNoz/signoz-otel-collector/issues/167#issuecomment-1727306380

**Pull request closed without merging**
